LPanels = {
	["Default"] = {
-----信息条面板-----

	{	name = "Litestats_hight", parent = "UIParent", x_off = -8, y_off = -6,
		width= "36%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.7,
	},

	{	name = "Litestats_middle", parent = "UIParent", x_off = -8, y_off = -11,
		width= "36%",
		height = 18, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.3,
	},

	{	name = "Litestats_low", parent = "UIParent", x_off = -8, y_off = -33,
		width= "36%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.7,
	},

-----聊天框左侧短线条-----
	
	{	name = "rAB_Short_Left4", parent = "ChatBorder_bottom_left", x_off = -14, y_off = 63.5,
		width= 14,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

	{	name = "rAB_Short_Left5", parent = "ChatBorder_bottom_left", x_off = -14, y_off = 28,
		width= 14,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

-----聊天框面板-----

	{	name = "Chat", parent = "UIParent", x_off = 14.5, y_off = 12,
		width= "24%",
		height = "18%", 
		strata = "BACKGROUND",
		--level = 1,
		anchor_to = "BOTTOMLEFT", 
		anchor_from = "BOTTOMLEFT",
		--tex_file ="Interface\\AddOns\\LitePanels\\media\\black", 
		bg_color = "0 0 0",
		bg_alpha = 0.6,
		
		--border ="Interface\\AddOns\\CWDGMediaPack\\Borders\\fer5",
		border_size = 14,
		inset = 1,
		inset = 1,
		border_color = "1 1 1",
		border_alpha = 0
	},

	{	name = "ChatBorder_left_top", parent = "Chat", x_off = 1, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

	{	name = "ChatBorder_left_bottom", parent = "Chat", x_off = 1, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 1,
	},
		
	{	name = "ChatBorder_right_top", parent = "Chat", x_off = -0.5, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "topright", 
		bg_color = "CLASS",
		bg_alpha = 1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

	{	name = "ChatBorder_right_bottom", parent = "Chat", x_off = -0.5, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "bottomright", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "ChatBorder_top_left", parent = "Chat", x_off = 0, y_off = 0,
		width= "50%",
		height = 2, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "ChatBorder_top_right", parent = "Chat", x_off = 0, y_off = 0,
		width= "50%",
		height = 2, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

	{	name = "ChatBorder_bottom_left", parent = "Chat", x_off = 0, y_off = 0,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "ChatBorder_bottom_right", parent = "Chat", x_off = 0, y_off = 0,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

-----rAB左侧(姿态条)短线条-----

	{	name = "rAB_Short_Left1", parent = "rABS_MainMenuBar", x_off = -16, y_off = 17,
		width= 1,
		height = "115%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.2,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "rAB_Short_Left2", parent = "rABS_MainMenuBar", x_off = -16, y_off = 17,
		width= "13%",
		height = 1.1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.2,
	},

	{	name = "rAB_Short_Left3", parent = "rABS_MainMenuBar", x_off = 28, y_off = 19,
		width= 8.2,
		height = 5.3, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

-----rAB主动作条线条-----

	{	name = "rAB_Middle1", parent = "rABS_MainMenuBar", x_off = 82, y_off = 0,
		width= "166%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "CENTER", 
		bg_color = "CLASS",
		bg_alpha = 0.7,
	},

	{	name = "rAB_Middle2", parent = "rABS_MainMenuBar", x_off = 82, y_off = -28,
		width= "166%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "CENTER", 
		bg_color = "CLASS",
		bg_alpha = 0.7,
	},

	{	name = "rAB_Middle3", parent = "rABS_MainMenuBar", x_off = 54, y_off = 17,
		width= "104%",
		height = 1, 
		strata = "BACKGROUND",
		level = 1,
		anchor_to = "TOP", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0,
	},

	{	name = "rAB_Middle4_left", parent = "rABS_MainMenuBar", x_off = -9, y_off = -38,
		width= "78%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},
			
	{	name = "rAB_Middle4_right", parent = "rABS_MainMenuBar", x_off = 178, y_off = -38,
		width= "78%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

-----rAB右侧短线条-----

	{	name = "rAB_Short_Left1", parent = "rABS_MultiBarBottomRight", x_off = 90, y_off = 3,
		width= 1,
		height = "53%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.2,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "rAB_Short_Left2", parent = "rABS_MultiBarBottomRight", x_off = 90, y_off = 3,
		width= "47%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.2,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},

	{	name = "rAB_Short_Left3", parent = "rABS_MultiBarBottomRight", x_off = 46, y_off = 5,
		width= 8.2,
		height = 5.9, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

-----伤害记录(skada)面板-----

		{	name = "Skada", parent = "SkadaBarWindowSkada", x_off = 0, y_off = 1, --NumerationFrame
		width= "101%",
		--width= 2000,
		height = "101%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOM", 
		anchor_from = "BOTTOM",
		--tex_file ="Interface\\AddOns\\LitePanels\\media\\black", 
		bg_color = "0 0 0",
		bg_alpha = 0.4,
		
		--border ="Interface\\AddOns\\CWDGMediaPack\\Borders\\fer5",
		border_size = 14,
		inset = 1,
		inset = 1,
		border_color = "1 1 1",            --"1 1 1",
		border_alpha = 0
		
		},

		{	name = "Skada_left_top", parent = "Skada", x_off = 0, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
				
		},

		{	name = "Skada_left_bottom", parent = "Skada", x_off = 0, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 1,
				
		},
		
		{	name = "Skada_right_top", parent = "Skada", x_off = 0, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "topright", 
		bg_color = "CLASS",
		bg_alpha = 1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
				
		},

		{	name = "Skada_right_bottom", parent = "Skada", x_off = 0, y_off = 0,
		width= 1,
		height = "50%", 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "bottomright", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "V",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
				
		},

	{	name = "Skada_top_left", parent = "Skada", x_off = 0, y_off = 0,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.9,
				
		},

	{	name = "Skada_top_right", parent = "Skada", x_off = 0, y_off = 0,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.9,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
				
		},

	{	name = "Skada_bottom_left", parent = "Skada", x_off = 0, y_off = -1,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
				
		},

	{	name = "Skada_bottom_right", parent = "Skada", x_off = 0, y_off = -1,
		width= "50%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
				
		},

-----伤害记录(skada)右侧短线条-----

	{	name = "rAB_Short_Left4", parent = "Skada_bottom_right", x_off = 22, y_off = 66,
		width= 22,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "RIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

	{	name = "rAB_Short_Left5", parent = "Skada_bottom_right", x_off = 22, y_off = 29.5,
		width= 22,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "RIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

-----Minimap面板-----

	{	name = "Minimap1", parent = "Minimap", x_off = 10, y_off = 14,
		width= "16%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},
			
	{	name = "Minimap2", parent = "Minimap", x_off = -12, y_off = 14,
		width= "16%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

	{	name = "Minimap3_left", parent = "Minimap", x_off = 5, y_off = 8,
		width= "46%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},
			
	{	name = "Minimap3_right", parent = "Minimap", x_off = -7, y_off = 8,
		width= "46%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "TOPRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},


	{	name = "Minimap4_left", parent = "Minimap", x_off = 4.5, y_off = -8,
		width= "47%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMLEFT", 
		bg_color = "CLASS",
		bg_alpha = 0.1,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.8,
	},
			
	{	name = "Minimap4_right", parent = "Minimap", x_off = -6.5, y_off = -8,
		width= "47%",
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "BOTTOMRIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
		gradient = "H",
		gradient_color = "CLASS",
		gradient_alpha = 0.1,
	},

-----小地图右侧短线条-----

	{	name = "rAB_Short_Left4", parent = "Minimap4_right", x_off = 22, y_off = 64,
		width= 17,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "RIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},

	{	name = "rAB_Short_Left5", parent = "Minimap4_right", x_off = 22, y_off = 29.5,
		width= 17,
		height = 1, 
		strata = "BACKGROUND",
		level = 4,
		anchor_to = "RIGHT", 
		bg_color = "CLASS",
		bg_alpha = 0.8,
	},
	},
}

--end

--hooksecurefunc(PetBattleFrame, 'Show', function() 123:Hide() end)
--hooksecurefunc(PetBattleFrame, 'Hide', function() 123:Show() end)